### ISSUE TITLE
Improvement on Cross-platform jar section

### ISSUE THREAD

**Issue by jukkaleh** [openjfx/openjfx-docs#133]
Originally our project pom had 3 openjfx dependencies declared in the pom. Worked great locally on windows.

```
<!-- https://mvnrepository.com/artifact/org.openjfx/javafx-controls -->
<dependency>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-controls</artifactId>
    <version>${javafx.version}</version>
    <classifier>win</classifier>
</dependency>
<!-- https://mvnrepository.com/artifact/org.openjfx/javafx-web -->
<dependency>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-web</artifactId>
    <version>${javafx.version}</version>
    <classifier>win</classifier>
    </dependency>
<!-- https://mvnrepository.com/artifact/org.openjfx/javafx-swing -->
<dependency>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-swing</artifactId>
    <version>${javafx.version}</version>
    <classifier>win</classifier>
</dependency>
```
Then the package was assembled by linux based CI-pipeline and the javafx parts wouldn't work on windows anymore because of:

```
java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at javafx.embed.swing.JFXPanel.lambda$initFx$1(JFXPanel.java:234)
	at java.base/java.lang.Thread.run(Thread.java:830)
```
Okay, it's seems that openjfx only downloads binaries for the system its built on. Let's add windows classifier for out three dependencies.
```
<classifier>win</classifier>
```
Maven would download linux and windows binaries for our three dependencies javafx-controls, javafx-web, javafx-swing. That should do it.... Nope still wouldn't work on windows same error about toolkit not found. Here is the part about banging head against a wall for while. Eventually after long time It dawned that these dependencies depend on javafx-graphics. Even though we had declared windows classifier in our pom it wouldn't affect openjfx's dependencies. The solution was to add all of the openjfx's dependencies by hand to our pom and add the classifier by hand.

The final pom that worked looked liked this. To ease other peoples suffering please add to openjfx documentation that you will need to manually add openjfx's internal dependencies to your pom and apply classifier for every platform (mac, linux, windows) you wish to support .

```
<!-- https://mvnrepository.com/artifact/org.openjfx/javafx-base -->
<dependency>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-base</artifactId>
    <version>${javafx.version}</version>
    <classifier>win</classifier>
</dependency>
<!-- https://mvnrepository.com/artifact/org.openjfx/javafx-graphics -->
<dependency>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-graphics</artifactId>
    <version>${javafx.version}</version>
    <classifier>win</classifier>
</dependency>
<!-- https://mvnrepository.com/artifact/org.openjfx/javafx-media -->
<dependency>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-media</artifactId>
    <version>${javafx.version}</version>
    <classifier>win</classifier>
</dependency>
<!-- https://mvnrepository.com/artifact/org.openjfx/javafx-controls -->
<dependency>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-controls</artifactId>
    <version>${javafx.version}</version>
    <classifier>win</classifier>
</dependency>
<!-- https://mvnrepository.com/artifact/org.openjfx/javafx-web -->
<dependency>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-web</artifactId>
    <version>${javafx.version}</version>
    <classifier>win</classifier>
</dependency>
<!-- https://mvnrepository.com/artifact/org.openjfx/javafx-swing -->
<dependency>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-swing</artifactId>
    <version>${javafx.version}</version>
    <classifier>win</classifier>
</dependency>
```

**Comment by ioliano** [comment]
@jukkaleh 
On the documentation of building with even it has the following description


> Run HelloWorld using Maven
If you want to develop JavaFX applications using Maven, you don't have to download the JavaFX SDK. Just specify the modules and the versions you want in the pom.xml, and the **build system will download the required modules, including the native libraries for your platform**.

But I agree with you, this goes totally against the way java is supposed to be "build once, run anywhere"

Did you managed to find a way to solve it? I have exactly the same issue, and I don't want to clone my project to windows just to build and have a "local windows version built"

**Comment by jukkaleh** [comment]
@ioliano Yes I was able to solve this. 
From the first message see 

> dependencies depend on javafx-graphics. Even though we had declared windows classifier in our pom it wouldn't affect openjfx's dependencies. The solution was to add all of the openjfx's dependencies by hand to our pom and add the classifier by hand.

**Comment by ioliano** [comment]
So in the end you did something like this ?
<dependency>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-controls</artifactId>
    <version>15.0.1</version>
     <classifier>win</classifier>
  </dependency>
<dependency>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-controls</artifactId>
    <version>15.0.1</version>
  </dependency>

**Comment by jukkaleh** [comment]
First post contains the starting pom we had and, 3 dependencies. The final pom at the end of the post has all the classifiers and dependencies which where required to make those 3 dependencies work on windows when built on linux.

I cant really remember more, this was a long time ago. Everything relevant is in the first post.
