### ISSUE TITLE
com.sun.webkit.dom.DocumentImpl.importNode() doesn't work

### ISSUE THREAD

**Issue by christianhujer** [openjfx/openjfx-docs#134]
The purpose of `org.w3c.dom.Document.importNode()` is to import nodes from other documents, and it should work across different implementations of the DOM. `com.sun.webkit.dom.DocumentImpl.importNode()` fails to do so by assuming that the `Node` is imported from the same `DOMImplementation` by casting it to `com.sun.webkit.dom.NodeImpl` instead of reflectively using the DOM API to traverse the imported node during import.

This makes it impossible to import nodes that have been generated by another DOM API, like the Xerces shipped with the JDK or another version of Xerces.

Sample StackTrace:
```
java.lang.ClassCastException: class org.apache.xerces.dom.ElementNSImpl cannot be cast to class com.sun.webkit.dom.NodeImpl (org.apache.xerces.dom.ElementNSImpl and com.sun.webkit.dom.NodeImpl are in unnamed module of loader 'app')
        at com.sun.webkit.dom.NodeImpl.getPeer(NodeImpl.java:226)
        at com.sun.webkit.dom.DocumentImpl.importNode(DocumentImpl.java:1083)
        at com.nelkinda.pocjfxswing.Main.lambda$open$2(Main.java:105)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        at java.base/java.lang.Thread.run(Thread.java:830)
```

OpenJFX Version: OpenJFX 14-ea+7

**Comment by christianhujer** [comment]
Oops, reported on the wrong project.

**Comment by fithisux** [comment]
> Oops, reported on the wrong project.

Did you find a solution?
