### ISSUE TITLE
TitledPane inside ListView that is inside a ListView throws NullPointerException when scrolling using mouse wheel.

### ISSUE THREAD

**Issue by sedj601** [openjfx/openjfx-docs#138]
Related to StackOverflow question [Getting NullPointerException and can't understand why](https://stackoverflow.com/questions/60198041/getting-null-pointer-exception-and-cant-understand-why?noredirect=1#comment106501717_60198041).

- This happens only when scrolling with the mouse wheel.
- This happens only when scrolling down.
- This happens only if a TitledPane near the top has been expanded once (doesn't matter whether it has been collapsed immediately after expanding).
- This has been tested using JavaFX11 and JavaFX13 on Windows10.
- I did not test to see if it would throw the same error if it was simply a TitledPane in a ListView.

The simplest steps to duplicate issue:

- Open the first TitledPane. 
- Start scrolling down using the mouse wheel.

**Error Message**
```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at javafx.controls/javafx.scene.control.skin.VirtualFlow$3.findOwnerCell(VirtualFlow.java:645)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow$3.select(VirtualFlow.java:619)
	at javafx.graphics/com.sun.javafx.scene.traversal.TraversalEngine.select(TraversalEngine.java:104)
	at javafx.graphics/com.sun.javafx.scene.traversal.TopMostTraversalEngine.trav(TopMostTraversalEngine.java:77)
	at javafx.graphics/javafx.scene.Scene.traverse(Scene.java:2092)
	at javafx.graphics/javafx.scene.Scene.focusIneligible(Scene.java:2111)
	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.focusCleanup(Scene.java:2447)
	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2462)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:412)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:411)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:438)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:563)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:543)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:536)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:342)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:830)
```
**Main**
```
import java.util.ArrayList;
import java.util.List;
import javafx.application.Application;
import static javafx.application.Application.launch;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.ListCell;
import javafx.scene.control.ListView;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;

public class NPEDiggingSO extends Application
{

    private static class OuterListCell extends ListCell<MainListViewCellData>
    {
        private final ListView<Note> cellListView;

        public OuterListCell()
        {
            setPrefHeight(300);
            setPrefWidth(300);

            cellListView = new ListView<>();
            cellListView.setCellFactory(v -> new NoteCell());
        }

        @Override
        protected void updateItem(MainListViewCellData item, boolean empty)
        {
            super.updateItem(item, empty);
            if (item == null || empty) {
                setText(null);
                setGraphic(null);
            }
            else {
                cellListView.getItems().setAll(item.getNotes());
                setGraphic(cellListView);
            }
        }

    }

    private Parent createContent()
    {
        ObservableList<MainListViewCellData> observableList = FXCollections.observableArrayList();

        for (int i = 0; i < 250; i++) {
            MainListViewCellData mainListViewCellData = new MainListViewCellData();
            List<Note> notes = new ArrayList();
            notes.add(new Note("note title " + i, "note text " + 1));
            mainListViewCellData.setNotes(notes);
            observableList.add(mainListViewCellData);
        }

        ListView<MainListViewCellData> outer = new ListView();
        outer.setItems(observableList);
        outer.setCellFactory(c -> new OuterListCell());
        BorderPane content = new BorderPane(outer);
        return content;
    }

    @Override
    public void start(Stage stage) throws Exception
    {
        stage.setScene(new Scene(createContent(), 700, 500));
        stage.setTitle("NPEDiggingSO");
        stage.show();
    }

    public static void main(String[] args)
    {
        launch(args);
    }
}
```
**MainListViewCellData**
```
import java.util.List;
import javafx.collections.FXCollections;

public class MainListViewCellData
{
    private List<Note> notes;

    public MainListViewCellData(List<Note> notes)
    {
        this.notes = notes;
    }

    public MainListViewCellData()
    {
        this.notes = FXCollections.observableArrayList();
    }

    public List<Note> getNotes()
    {
        return notes;
    }

    public void setNotes(List<Note> notes)
    {
        this.notes = notes;
    }

    @Override
    public String toString()
    {
        return '{' + "notes=" + notes + '}';
    }
}
```
**Note**
```
public class Note
{
    private String title;
    private String text;

    public Note(String title, String text)
    {
        this.title = title;
        this.text = text;
    }

    public String getText()
    {
        return text;
    }

    public void setText(String text)
    {
        this.text = text;
    }

    public String getTitle()
    {
        return title;
    }

    public void setTitle(String title)
    {
        this.title = title;
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append(", title=").append(title);
        sb.append(", text=").append(text);
        sb.append('}');
        return sb.toString();
    }
}
```
**NoteCell**

```public class NoteCell extends ListCell<Note>
{
    TextArea textArea = new TextArea();
    TitledPane titledPane = new TitledPane("", textArea);
    ObservableList<Note> observableList = FXCollections.observableArrayList();

    @Override
    public void updateItem(Note item, boolean empty)
    {
        super.updateItem(item, empty);
        if (item == null || empty) {
            setText(null);
            setGraphic(null);
        }
        else {
            titledPane.setExpanded(false);
            titledPane.setText(item.getTitle());
            titledPane.setAnimated(false);
            textArea.setText(item.getText());
            setGraphic(titledPane);
        }
    }
}
```

**Comment by abhinayagarwal** [comment]
Not related to openjfx-docs. Please report the issue on other forums like StackOverflow :)
